# Random numbers

Random number generators are defined in package `numpy`. See: https://numpy.org/doc/stable/reference/random/

The following example throws a fair coin where `True` represents head and `False` is tail (i.e., head is false).

In [2]:
import numpy as np  

# initialize a new random number generator
rng = np.random.default_rng()

p = .5

for i in range(5): 
    print(rng.random() < p)

False
True
False
True
False


A useful function is `random.choice`. Here is again a fair coin.

In [3]:
rng.choice([True, False], size = 5, p = [p, 1-p])

array([ True, False,  True, False, False])

# Multi-dimensional arrays

Package `numpy` provides a convenient way to work with multi-dimensional arrays.

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
# access values using row and column index
arr[0, 0]

1

In [6]:
# sum all elements of the array
np.sum(arr)

21

In [7]:
# dot product
np.dot([1, 2], arr)

array([ 9, 12, 15])

In [8]:
# reshape array dimenstions
newarr = arr.reshape(3, 2)
newarr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [2]:
%run Andy.py
%run Bill.py



SyntaxError: invalid syntax (random_numbers_and_arrays.ipynb, line 52)

True
False
True
True
True
[[1 2 3]
 [4 5 6]]
